var scaleNames = {
	5: ["Vietnamese ditonic"],
	33: ["Honchoshi"],
	41: ["Vietnamese tritonic"],
	129: ["Niagari"],
	137: ["Ute tritonic","Peruvian tritonic 2"],
	145: ["Raga Malasri","Peruvian tritonic 1"],
	149: ["Eskimo tetratonic"],
	161: ["Raga Sarvasri","Warao tritonic"],
	165: ["Genus Primum"],
	169: ["Vietnamese tetratonic"],
	173: ["Raga Purnalalita","Chad Gadyo","Ghana Pentatonic 1","Nando-kyemyonjo"],
	181: ["Raga Budhamanohari"],
	193: ["Raga Ongkari"],
	195: ["Messiaen truncated mode 5"],
	199: ["Raga Nabhomani"],
	219: ["Istrian"],
	245: ["Raga Dipak"],
	273: ['Augmented Triad'],
	291: ["Raga Lavangi","Gowleeswari"],
	293: ["Raga Haripriya"],
	299: ["Raga Chitthakarshini"],
	301: ["Raga Audav Tukhari"],
	307: ["Raga Megharanjani","Syrian Pentatonic"],
	325: ["Messiaen truncated mode 6"],
	331: ["Raga Chhaya Todi","Locrian Pentatonic 1"],
	395: ["Phrygian Pentatonic","Balinese Pelog","Madenda Modern","Raga Bhupalam","Bhupala Todi","Bibhas"],
	395: ['Balinese'],
	397: ["Aeolian Pentatonic","Hira-joshi","Kata-kumoi","Yona Nuki Minor","Tizita Minor (Half tizita)"],
	397: ['Hirajoshi'],
	403: ["Raga Reva","Revagupti","Ramkali","Vibhas (Bhairava)"],
	405: ["Raga Bhupeshwari","Janasammodini"],
	419: ["Hon-kumoi-joshi","Sakura","Akebono II","Olympos Enharmonic","Raga Salanganata","Saveri","Gunakri (Gunakali)","Latantapriya","Ambassel",'japanese (a)'],
	421: ["Han-kumoi","Raga Shobhavari","Sutradhari",'japenese (b)'],
	425: ["Raga Kokil Pancham"],
	427: ["Raga Suddha Simantini"],
	433: ["Raga Zilaf"],
	435: ["Raga Purna Pancama","Malahari","Geyahejjajji","Kannadabangala"],
	451: ["Raga Saugandhini","Yashranjani"],
	455: ["Messiaen mode 5","Two-semitone Tritone scale"],
	461: ["Raga Syamalam"],
	467: ["Raga Dhavalangam"],
	529: ["Raga Bilwadala"],
	549: ["Raga Bhavani"],
	557: ["Raga Abhogi"],
	585: ['Diminished Seventh'],
	597: ["Kung"],
	619: ["Double-Phrygian Hexatonic"],
	621: ["Pyramid Hexatonic"],
	637: ["Debussy's Heptatonic"],
	653: ["Dorian Pentatonic","Raga Sivaranjini","Raga Shivranjani","Akebono I",'Kumoi'],
	659: ["Raga Rasika Ranjani","Vibhas (Marva)","Scriabin"],
	661: ["Major Pentatonic","Pentatonic Major","Ryosen","Yona Nuki Major","Man Jue","Gong","Raga Bhopali","Raga Bhup","Mohanam","Deskar","Bilahari","Kokila","Jait Kalyan","Peruvian Pentatonic 1","Ghana Pentatonic 2","Tizita Major"],
	665: ["Raga Mohanangi"],
	675: ["Altered Pentatonic","Raga Manaranjani II"],
	677: ["Scottish Pentatonic","Blues Major","Ritusen","Ritsu","Gagaku","Zhi","Zheng","Ujo","P'yongjo","Bac","Lai Soutsanaen","Lai Po Sai","Lai Soi","Raga Devakriya","Durga","Suddha Saveri","Arabhi","Major complement"],
	681: ["Kyemyonjo","Minor added sixth Pentatonic"],
	685: ["Raga Suddha Bangala","Gauri Velavali"],
	689: ["Raga Nagasvaravali","Raga Mand"],
	691: ["Raga Kalavati","Ragamalini"],
	693: ["Arezzo Major Diatonic Hexachord","Raga Kambhoji","Devarangini","Sama","Syama","Scottish Hexatonic"],
	709: ["Raga Shri Kalyan"],
	711: ["Raga Chandrajyoti"],
	715: ["Messiaen truncated mode 2"],
	717: ["Raga Vijayanagari"],
	721: ["Raga Dhavalashri"],
	725: ["Raga Yamuna Kalyani","Kalyani Keseri","Airavati","Ancient Chinese"],
	743: ["Chromatic Hypophrygian inverse"],
	775: ["Raga Putrika"],
	807: ["Raga Suddha Mukhari"],
	819: ["Augmented Inverse","Messiaen truncated mode 3","Prometheus (Liszt)","Six Tone Symmetrical"],
	845: ["Raga Neelangi"],
	851: ["Raga Hejjajji"],
	859: ["Ultralocrian","Superlocrian Diminished","Superlocrian Double-Flat 7","Mixolydian sharp 1","Diminished"],
	871: ['Locrian Double-flat 3 Double-flat 7'],
	875: ["Locrian Double-flat 7"],
	877: ["Moravian Pistalkova","Hungarian Major inverse"],
	915: ["Raga Kalagada","Raga Kalgada"],
	919: ["Chromatic Phrygian Inverse"],
	923: ['Ultraphrygian'],
	925: ["Chromatic Hypodorian","Relative Blues scale","Raga Dvigandharabushini"],
	931: ["Raga Kalakanthi"],
	935: ["Chromatic Dorian","Mela Kanakangi","Raga Kanakambari"],
	939: ["Mela Senavati","Raga Senagrani","Malini"],
	941: ["Mela Jhankaradhvani","Raga Jhankara Bhramavi"],
	945: ["Raga Saravati","Raga Sharavati"],
	947: ["Mela Gayakapriya","Raga Kalakanti","Romani Hexatonic"],
	949: ["Mela Mararanjani","Raga Keseri","Major Bebop Heptatonic"],
	953: ["Mela Yagapriya","Raga Kalahamsa"],
	967: ["Mela Salaga","Mela Salagam"],
	971: ["Mela Gavambodhi","Raga Girvani"],
	973: ["Mela Syamalangi","Raga Shyamalam"],
	975: ["Messiaen mode 4","Tcherepnin Octatonic mode 3"],
	979: ["Mela Dhavalambari","Foulds' Mantra of Will scale"],
	981: ["Mela Kantamani","Raga Kuntala","Srutiranjani"],
	985: ["Mela Sucaritra","Raga Santanamanjari"],
	1025: ["Warao ditonic"],
	1037: ["Warao tetratonic"],
	1057: ["Sansagari"],
	1105: ["Messiaen truncated mode 6 inverse"],
	1113: ["Locrian Pentatonic 2"],
	1115: ["Superlocrian Hexamirror"],
	1123: ["Iwato"],
	1129: ["Raga Jayakauns"],
	1131: ["Honchoshi plagal form"],
	1161: ["Bi Yu"],
	1163: ["Raga Rukmangi"],
	1169: ["Raga Mahathi","Antara Kaishiaki"],
	1171: ["Raga Manaranjani I"],
	1173: ["Dominant Pentatonic"],
	1185: ["Genus Primum Inverse"],
	1187: ["Kokin-joshi","Miyakobushi","Han-Iwato","In Sen","Raga Vibhavari","Bairagi","Lasaki"],
	1189: ["Suspended Pentatonic","Raga Madhyamavati","Madhmat Sarang","Megh","Egyptian","Shang","Rui Bin","Jin Yu","Qing Yu","Yo","Ngu Cung Dao","Yematebela wofe","Egyptian"],
	1193: ["Minor Pentatonic","Pentatonic Minor","Blues Pentatonic","Raga Dhani","Abheri","Udhayaravi Chandrika","Qing Shang","Gu Xian","Jia Zhong","Yu","P'yongjo-kyemyonjo","Minyo","Lai Yai","Lai Noi","Nam","Northern Sa mac","Peruvian Pentatonic 2","Batti Minor"],
	1195: ["Raga Gandharavam","Sabai silt"],
	1197: ["Minor Hexatonic","Raga Manirangu","Nayaki","Palasi","Pushpalithika","Puspalatika","Suha Sughrai","Yo","Eskimo Hexatonic 1"],
	1201: ["Mixolydian Pentatonic","Nam ai","Oan","Raga Savethri"],
	1205: ["Raga Siva Kambhoji","Vivardhini","Andhali"],
	1209: ["Raga Bhanumanjari","Jog"],
	1225: ["Raga Samudhra Priya","Madhukauns"],
	1229: ["Raga Simharava","Raga Sinharavam","Gopikatilaka"],
	1235: ["Messiaen truncated mode 2","Raga Indupriya","Tritone scale"],
	1255: ["Chromatic Mixolydian"],
	1257: ["Blues scale","Blues","Raga Nileshwari"],
	1261: ["Modified Blues"],
	1317: ["Chaio"],
	1321: ["Blues Minor","Raga Malkauns","Raga Malakosh","Raga Hindola","Man Gong","Quan Ming","Yi Ze","Jiao","Shegaye"],
	1323: ["Ritsu","Raga Suddha Todi)"],
	1331: ["Raga Vasantabhairavi"],
	1335: ["Elephant"], // https://www.youtube.com/watch?v=f4eXdIlXZ7k
	1353: ["Raga Harikauns","Chin"],
	1355: ["Raga Bhavani"],
	1357: ["Takemitsu Tree Line mode 2"],
	1365: ["Whole-tone","Messiaen mode 1","Raga Gopriya","Anhemitonic Hexatonic",'auxiliary augmented'],
	1367: ["Leading Whole-Tone inverse"],
	1371: ["Superlocrian","Altered Dominant","Diminished Whole-tone","Locrian flat 4","Pomeroy","Ravel","Dominant Whole-tone Combo","Altered"],
	1387: ["Locrian","Half Diminished Locrian","Greek Mixolydian","Greek Hyperdorian","Medieval Hypophrygian","Medieval Locrian","Greek Medieval Hyperaeolian","Rut biscale descending","Pien chih","Makam Lami","Yishtabach"],
	1389: ["Minor Locrian","Half Diminished","Locrian Sharp 2","Minor Flat 5"],
	1395: ["Asian (a)"],
	1397: ["Major Locrian",'Arabian b'],
	1403: ["Espla's scale","Eight-tone Spanish"],
	1417: ["Raga Shailaja","Varini"],
	1419: ["Raga Kashyapi"],
	1421: ["Raga Trimurti"],
	1431: ["Gummy Bear"], // https://www.youtube.com/watch?v=yx_VdGFaPJk
	1435: ["Makam Huzzam","Maqam Saba Zamzam","Phrygian Flat 4"],
	1437: ["Sabach ascending"],
	1443: ["Raga Phenadyuti","Insen","Honchoshi","Niagari"],
	1445: ["Raga Navamanohari"],
	1447: ["Mela Ratnangi","Raga Phenadyuti"],
	1449: ["Raga Gopikavasantam","Desya Todi","Jayantasri","Phrygian Hexatonic"],
	1451: ["Phrygian","Greek Dorian","Medieval Phrygian","Greek Medieval Hypoaeolian","Neopolitan Minor","Bhairavi That","Bhairavi Theta","Mela Hanumatodi","Raga Asavari","Raga Asaveri","Bilashkhani Todi","Ghanta","Makam Kurd","Gregorian nr.3","In","Zokuso","Ousak","Major inverse"],
	1453: ["Aeolian","Greek Medieval Hypodorian","Greek Medieval Aeolian","Greek Hyperphrygian","Minor","Natural Minor","Pure Minor","Melodic Minor descending","Asavari That","Asavari Theta","Mela Natabhairavi","Raga Jaunpuri","Adana","Darbari","Dhanyasi","Jingla","Gregorian nr.2","Makam Buselik","Nihavend","Peruvian Minor","Se","Chiao","Geez/Ezel","Kiourdi descending","Cushak"],
	1455: ["Phrygian/Aeolian mixed"],
	1457: ["Raga Kamalamanohari"],
	1459: ["Phrygian Dominant","Phrygian Major","Spanish Romani","Mela Vakulabharanam","Raga Jogiya","Ahiri","Vativasantabhairavi","Zilof","Ahava Rabba","Freygish","Maqam Hijaz-Nahawand","Humayun","Dorico Flamenco","Hitzaz","Harmonic Major inverse","Altered Hungarian"],
	1461: ["Major-Minor","Melodic Major","Mischung 6","Mixolydian flat 6","Mela Carukesi","Raga Charukeshi","Tarangini","Hindu","Hindustan","Altered Mixolydian"],
	1465: ["Mela Ragavardhani","Raga Cudamani"],
	1467: ["Spanish Phrygian",'altered dominant a'],
	1477: ["Raga Jaganmohanam"],
	1479: ["Mela Jalarnava", 'mela jalarnavam'],
	1483: ["Mela Bhavapriya","Raga Bhavani","Kalamurti","Neveseri ascending"],
	1485: ["Minor Romani","Ukrainian Dorian","Mela Sanmukhapriya","Raga Camara","Chinthamani","Lydian Diminished","Aolian Sharp 4","Romani Scale"],
	1489: ["Raga Jyoti"],
	1491: ["Mela Namanarayani","Raga Narmada","Pratapa","Harsh Major-Minor"],
	1493: ["Lydian Minor","Minor Lydian","Mela Risabhapriya","Raga Ratipriya"],
	1495: ["Messiaen mode 6"],
	1497: ["Mela Jyotisvarupini","Raga Jotismatti"],
	1499: ["Bebop Locrian", 'Altered Dominant b'],
	1515: ["Phrygian/Locrian mixed"],
	1519: ["Locrian/Aeolian mixed"],
	1573: ["Raga Guhamanohari"],
	1577: ["Raga Chandrakauns (Kafi)","Surya","Varamu"],
	1581: ["Raga Bagesri","Sriranjani","Kapijingla","Jayamanohari"],
	1585: ["Raga Khamaji Durga"],
	1587: ["Raga Rudra Pancama"],
	1589: ["Raga Rageshri","Raga Rageshwari","Nattaikurinji","Natakuranji"],
	1619: ["Prometheus Neapolitan"],
	1621: ["Prometheus (Scriabin)","Mystic","Raga Barbara)"],
	1643: ["Locrian natural 6","Maqam Tarznauyn",'Locrian Sharp 6'],
	1645: ["Dorian flat 5","Blues Heptatonic","Makam Karcigar","Maqam Nahawand Murassah","Kiourdi ascending","Kartzihiar"],
	1651: ["Asian","Asian (b)","Raga Ahira-Lalita","Hungarian Minor inverse","Tsinganikos"],
	1653: ["Minor Romani inverse"],
	1659: ["Maqam Shadd'araban"],
	1669: ["Raga Matha Kokila","Raga Matkokil"],
	1675: ["Raga Salagavarali"],
	1677: ["Raga Manavi"],
	1681: ["Raga Valaji"],
	1683: ["Raga Malayamarutam"],
	1697: ["Raga Kuntvarali","Raga Kuntalavarali"],
	1699: ["Raga Rasavali"],
	1701: ["Dominant Seventh","Mixolydian Hexatonic","P'yongjo","Yosen","Raga Darbar","Narayani","Suposhini","Andolika","Gorakh Kalyan"],
	1703: ["Mela Vanaspati","Raga Bhanumati"],
	1705: ["Raga Manohari","Malavasri"],
	1707: ["Mela Natakapriya","Jazz Minor inverse","Phrygian-Mixolydian","Dorian flat 2","Raga Natabharanam","Ahiri Todi","Javanese Pelog","Pelog"],
	1709: ["Dorian","Greek Phrygian","Medieval Dorian","Medieval Hypomixolydian","Kafi That","Kafi Theta","Mela Kharaharapriya","Raga Bageshri","Bhimpalasi","Nayaki Kanada","Sriraga","Ritigaula","Huseni","Kanara","Mischung 5","Gregorian nr.8","Eskimo Heptatonic","Yu","Hyojo","Oshikicho","Banshikicho","Nam"],
	1711: ["Adonai Malakh","Jewish"],
	1713: ["Raga Khamas","Desya Khamas","Bahudari"],
	1715: ["Harmonic Minor inverse","Mela Cakravaka","Mela Chakravakam","Raga Ahir Bhairav","Bindumalini","Vegavahini","Makam Hicaz","Zanjaran"],
	1717: ["Mixolydian","Greek Hypophrygian","Greek Ionian","Greek Iastian","Medieval Mixolydian","Greek Medieval Hypoionian","Hypermixolydian","Khamaj That","Khamaj Theta","Mela Harikambhoji","Raga Harini","Janjhuti","Khambhavati","Surati","Balahamsa","Devamanohari","Mischung 3","Gregorian nr.7","Enharmonic Byzantine Liturgical","Rast descending","Ching","Shang"],
	1721: ["Mela Vagadhisvari","Raga Bhogachayanata","Nandkauns","Ganavaridhi","Chayanata","Bluesy Rock 'n Roll"],
	1723: ["JG Octatonic"],
	1725: ["Minor Bebop","Dorian Bebop","Bebop Dorian","Raga Zilla","Mixolydian/Dorian mixed"],
	1733: ["Raga Sarasvati"],
	1735: ["Mela Navanitam","Raga Nabhomani"],
	1737: ["Raga Madhukauns"],
	1739: ["Mela Sadvidhamargini","Raga Sthavarajam","Tivravahini"],
	1741: ["Altered Dorian","Mela Hemavati","Raga Desisimharavam","Maqam Nakriz","Tunisian","Ukranian Dorian","Romanian Scale","Rumanian Minor","Dorian sharp 4","Misheberekh","Souzinak Minor","Peiraiotikos Minor","Nigriz","Pimenikos","Ukrainian Minor","Kaffa","Gnossiennes"],
	1745: ["Raga Vutari"],
	1747: ["Mela Ramapriya","Raga Ramamanohari","Romanian Major","Petrushka chord"],
	1749: ["Acoustic","Lydian Dominant","Mela Vacaspati","Raga Bhusavati","Bhusavali","Overtone","Overtone Dominant","Lydian-Mixolydian","Lydian-Mixolydian Combo","Bartok"],
	1753: ["Hungarian Major","Mela Nasikabhusani","Raga Nasamani"],
	1755: ["Octatonic","Messiaen mode 2","Dominant Diminished","Diminished Blues","Half-Whole step scale",'second mode of limited transposition','auxiliary diminished blues', 'dominant'],
	1769: ["Blues Heptatonic II"],
	1773: ["Blues scale II"],
	1783: ["Youlan scale"],
	1789: ["Blues Enneatonic II"],
	1849: ["Chromatic Hypodorian inverse"],
	1911: ["Messiaen mode 3","Tcherepnin Nonatonic mode 3"],
	1965: ["Raga Mukhari","Anandabhairavi","Deshi","Manji","Gregorian nr.1","Dorian/Aeolian mixed"],
	1967: ["Diatonic Dorian mixed"],
	1981: ["Houseini","Modes of Major Pentatonic mixed"],
	1997: ["Raga Cintamani"],
	2015: ["Messiaen mode 7"],
	2029: ["Kiourdi"],
	2043: ["Maqam Tarzanuyn"],
	2099: ["Raga Megharanji"],
	2117: ["Raga Sumukam"],
	2129: ["Raga Nigamagamini"],
	2133: ["Raga Kumurdaki","Raga Kumudki"],
	2145: ["Messiaen truncated mode 5 inverse"],
	2197: ["Raga Hamsadhvani","Raga Hansdhwani","Raga Haunsadhwani"],
	2211: ["Raga Gauri"],
	2213: ["Raga Desh","Tcherepnin Major Pentatonic","Nam xuan"],
	2217: ["Raga Nata","Udayaravicandrika","Madhuranjani"],
	2221: ["Raga Sindhura Kafi"],
	2225: ["Ionian Pentatonic","Raga Gambhiranata","Pelog Degung Modern","Ryukyu","Vong co","Batti Major"],
	2227: ["Raga Gaula"],
	2229: ["Raga Nalinakanti","Kedaram","Vilasini"],
	2245: ["Raga Vaijayanti","Hamsanada"],
	2247: ["Raga Vijayasri"],
	2249: ["Raga Multani","Batti mineur"],
	2253: ["Raga Amarasenapriya"],
	2257: ["Lydian Pentatonic","Raga Amritavarshini","Malashri","Shilangi","Batti Lydian",'Hirajoshi',"Chinese","Augmented"],
	2259: ["Raga Mandari","Gamakakriya","Hamsanarayani"],
	2261: ["Raga Caturangini","Ratnakanthi"],
	2265: ["Raga Rasamanjari"],
	2275: ["Messiaen Mode 5","Fifth Mode of Limited Transposition"],
	2311: ["Raga Kumarapriya"],
	2339: ["Raga Kshanika"],
	2341: ["Raga Priyadharshini"],
	2345: ["Raga Chandrakauns","Kiravani"],
	2347: ["Raga Viyogavarali"],
	2349: ["Raga Ghantana","Kaushiranjani","Kaishikiranjani"],
	2353: ["Raga Girija","Bacovia","Batti Major sharp 5"],
	2355: ["Raga Lalita","Sohini","Hamsanandi","Lalit Bhairav"],
	2357: ["Raga Sarasanana"],
	2379: ["Raga Gurjari Todi"],
	2381: ["Takemitsu Tree Line mode 1"],
	2389: ["Eskimo Hexatonic 2"],
	2413: ["Locrian nr.2"],
	2419: ["Raga Lalita","Persian","Chromatic Hypolydian inverse","Raga Suddha Pancama","Persian"],
	2435: ["Raga Deshgaur"],
	2451: ["Raga Bauli"],
	2453: ["Raga Latika"],
	2457: ["Major Augmented","Messiaen truncated mode 3 inverse","Genus Tertium","Raga Devamani","Augmented"],
	2465: ["Raga Devaranjani","Raga Devaranji"],
	2467: ["Raga Padi"],
	2469: ["Raga Bhinna Pancama"],
	2471: ["Mela Ganamurti","Raga Ganasamavarali"],
	2473: ["Raga Takka"],
	2475: ["Neapolitan Minor","Minor Neapolitan","Mela Dhenuka","Raga Bhinnasadjam","Dhunibinnashadjam","Kirvanti","Takka","Maqam Shahnaz Kurdi","Hungarian Romani"],
	2477: ["Harmonic Minor","Mischung 4","Pilu That","Mela Kiravani","Raga Kiranavali","Kirvani","Kalyana Vasantha","Deshi(3)","Maqam Bayat-e-Esfahan","Sultani Yakah","Zhalibny Minor","Armoniko minore","Mohammedan"],
//		2479: ["Harmonic and Neapolitan Minor mixed"],
	2481: ["Raga Paraju","Raga Paraz","Raga Pharas","Ramamanohari","Sindhu Ramakriya","Kamalamanohari"],
	2483: ["Double Harmonic","Major Romani","Hungarian Romani Persian","Double Harmonic Major","Enigmatic","Byzantine","Flamenco Mode","Bhairav That","Bhairav Theta","Mela Mayamalavagaula","Raga Paraj","Kalingada","Gaulipantu","Lalitapancamam","Chromatic 2nd Byzantine Liturgical","Hitzazkiar","Maqam Zengule","Hijaz Kar","Suzidil"],
	2485: ["Harmonic Major","Mela Sarasangi","Raga Haripriya","Simhavahini","Mischung 2","Ethiopian","Tabahaniotikos"],
	2489: ["Mela Gangeyabhusani","Raga Gangatarangini","Sengiach","Sengah","Romani Hexatonic inverse"],
	2503: ["Mela Jhalavarali","Raga Varali","Jinavali"],
	2507: ["Todi That","Todi Theta","Mela Shubhapantuvarali","Raga Multani","Gamakasamantam","Harsh Minor","Chromatic Lydian inverse","Maqam Athar Kurd"],
	2509: ["Double Harmonic Minor","Hungarian Minor","Egyptian Heptatonic","Mela Simhendramadhyama","Raga Madhava Manohari","Maqam Nawa Athar","Hisar","Flamenco Mode","Niavent"],
	2515: ["Chromatic Hypolydian","Purvi That","Purvi Theta","Mela Kamavardhani","Raga Shri","Pantuvarali","Basant","Kasiramakriya","Suddharamakriya","Puriya Dhanashri","Dhipaka","Pireotikos"],
	2517: ["Harmonic Lydian","Mela Latangi","Raga Gitapriya","Hamsalata"],
	2521: ["Mela Dhatuvardhani","Raga Dhauta Pancama","Devarashtra"],
	2535: ["Messiaen mode 4","Tcherepnin Octatonic mode 2",'Fourth mode of limited transposition'],
	2539: ["Half-diminished Bebop"],
	2541: ["Algerian","Sabiren"],
	2547: ["Raga Ramkali","Raga Ramakri)"],
	2581: ["Raga Neroshta"],
	2597: ["Raga Rasranjani"],
	2601: ["Raga Chandrakauns","Marga Hindola","Rajeshwari"],
	2609: ["Raga Bhinna Shadja","Kaushikdhvani","Hindolita"],
	2611: ["Raga Vasanta","Chayavati"],
	2613: ["Raga Hamsa Vinodini"],
	2629: ["Raga Shubravarni"],
	2637: ["Raga Ranjani","Rangini"],
	2641: ["Raga Hindol","Sunada Vinodini","Sanjh ka Hindol"],
	2643: ["Raga Hamsanandi","Marva","Pancama","Puriya","Sohni"],
	2645: ["Raga Mruganandana"],
	2669: ["Jeths' mode"],
	2675: ["Chromatic Lydian","Raga Lalit","Bhankar"],
	2701: ["Hawaiian"],
	2705: ["Raga Mamata"],
	2709: ["Raga Kumud","Sankara","Shankara","Prabhati","Lydian Hexatonic"],
	2721: ["Raga Puruhutika","Purvaholika"],
	2723: ["Raga Jivantika"],
	2725: ["Raga Nagagandhari"],
	2727: ["Mela Manavati","Raga Manoranjani"],
	2731: ["Neapolitan Major","Major Meapolitan","Lydian Major","Mela Kokilapriya","Raga Kokilaravam"],
	2733: ["Melodic Minor ascending","Melodic Minor",'Heptatonia Seconda', "Jazz Minor","Minor-Major","Mela Gaurimanohari","Raga Patdip","Velavali","Deshi(2)","Mischung 1","Hawaiian"],
	2737: ["Raga Hari Nata","Genus Secundum"],
	2739: ["Mela Suryakanta","Mela Suryakantam","Bhairubahar That","Raga Supradhipam","Sowrashtram","Jaganmohini","Major-Melodic Phrygian","Hungarian Romani inverse"],
	2741: ["Major","Ionian","Greek Lydian","Medieval Ionian","Medieval Hypolydian","Major","Bilaval That","Bilaval Theta","Mela Shankarabharanam","Mela Dhirasankarabharana","Raga Atana","Ghana Heptatonic","Peruvian Major","Matzore","Rast ascending","4th plagal Byzantine","Ararai","Makam Cargah","Ajam Ashiran","Dastgah-e Mahur","Dastgah-e Rast Panjgah","Xin","DS2"],
	2745: ["Mela Sulini","Raga Sailadesakshi","Raga Trishuli","Houzam"],
	2757: ["Raga Nishadi"],
	2759: ["Mela Pavani","Raga Kumbhini"],
	2763: ["Mela Suvarnangi","Raga Sauviram"],
	2765: ["Lydian Diminished","Mela Dharmavati","Raga Arunajualita","Dumyaraga","Madhuvanti","Ambika"],
	2771: ["Marva That","Marva Theta","Mela Gamanasrama","Raga Partiravam","Puriya","Puriya Kalyan","Purvikalyani","Sohani","Bairari","Harsh-intense Major","Peiraiotikos"],
	2773: ["Lydian","Greek Hypolydian","Medieval Lydian","Greek Medieval Hypolocrian","Rut biscale ascending","Kalyan That","Kalyan Theta","Mela Mecakalyani","Raga Shuddh Kalyan","Ping","Kung","Gu"],
	2777: ["Aeolian Harmonic","Lydian sharp 2","Mela Kosalam","Raga Kusumakaram"],
	2779: ["Shostakovich"],
	2795: ["Van der Horst Octatonic"],
	2803: ["Raga Bhatiyar"],
	2805: ["Ishikotsucho","Raga Yaman Kalyan","Chayanat","Bihag","Hamir Kalyani","Kedar","Gaud Sarang","Genus Diatonicum Veterum Correctum","Gregorian nr.5","Kubilai's Mongol scale","Major/Lydian mixed"],
	2869: ["Ionian Augmented","Ionian sharp 5"],
	2873: ['Ionian Augmented Sharp 2'],
	2901: ["Lydian Augmented","Lydian sharp 5"],
	2905: ["Aeolian flat 1"],
	2907: ["Magen Abot"],
	2917: ["Nohkan Flute scale"],
	2925: ["Diminished","Modus conjunctus","Messiaen mode 2 inverse","Whole-Half step scale","Auxiliary Diminished","Arabian A"],
	2987: ["Neapolitan Major and Minor mixed"],
	2989: ["Bebop Minor","Zirafkend","Melodic Minor Bebop","Minor Bebop"],
	2995: ["Raga Saurashtra"],
	2997: ["Major Bebop","Altered Mixolydian","Bebop Major"],
	2999: ["Chromatic and Permuted Diatonic Dorian mixed"],
	3003: ["Genus Chromaticum","Tcherepnin Nonatonic mode 1","Augmented-9"],
	3037: ["nine tone scale"],
	3055: ["Messiaen mode 7",'seventh mode of limited transposition'],
	3069: ["Maqam Shawq Afza"],
	3185: ["Messiaen mode 5 inverse"],
	3237: ["Raga Brindabani Sarang","Megh","Megh Malhar"],
	3239: ["Mela Tanarupi","Raga Tanukirti"],
	3243: ["Mela Rupavati"],
	3245: ["Mela Varunapriya","Viravasantham"],
	3249: ["Raga Tilang","Savitri","Brindabani Tilang"],
	3251: ["Mela Hatakambari","Raga Jeyasuddhamalavi"],
	3253: ["Mela Naganandini","Raga Nagabharanam","Samanta"],
	3257: ["Mela Calanata","Raga None","Chromatic Dorian inverse"],
	3269: ["Raga Malarani","Hamsanada"],
	3271: ["Mela Raghupriya","Raga Ravikriya","Ghandarva"],
	3273: ["Raga Jivantini","Gaurikriya"],
	3275: ["Mela Divyamani"],
	3277: ["Mela Nitimati","Raga Nisada","Kaikavasi"],
	3281: ["Raga Vijayavasanta"],
	3283: ["Mela Visvambhari","Raga Vamsavathi"],
	3285: ["Mela Citrambari","Raga Chaturangini"],
	3289: ["Lydian Sharp 2 Sharp 6","Mela Rasikapriya","Raga Rasamanjari","Hamsagiri"],
	3301: ["Chromatic Mixolydian inverse"],
	3305: ["Chromatic Hypophrygian","Blues scale III"],
	3315: ["Tcherepnin Octatonic mode 1"],
	3379: ["Verdi's Scala enigmatica descending"],
	3385: ["Chromatic Phrygian"],
	3411: ["Enigmatic","Verdi's Scala enigmatica ascending"],
	3413: ["Leading Whole-tone"],
	3419: ["Magan Abot"],
	3435: ["Prokofiev"],
	3443: ["Verdi's Scala enigmatica"],
	3445: ["Messiaen mode 6 inverse",'sixth mode of limited transposition'],
	3485: ["Sabach","Sambah"],
	3499: ["Hamel"],
	3501: ["Maqam Nahawand","Farahfaza","Raga Suha","Raga Suha Kanada","Gregorian nr.4","Utility Minor"],
	3507: ["Maqam Hijaz","Maqam Hedjaz"],
	3515: ["Moorish Phrygian","Phrygian/Double Harmonic Major mixed"],
	3519: ["Raga Sindhi-Bhairavi"],
	3531: ["Neveseri"],
	3549: ["Messiaen mode 3 inverse","Tcherepnin Nonatonic mode 2",'third mode of limited transposition'],
	3575: ["Symmetrical Decatonic"],
	3637: ["Raga Rageshri"],
	3705: ["Messiaen mode 4 inverse","Tcherepnin Octatonic mode 4"],
	3749: ["Raga Sorati","Sur Malhar"],
	3757: ["Raga Mian Ki Malhar","Bahar","Sindhura"],
	3761: ["Raga Madhuri"],
	3765: ["Dominant Bebop","Genus Diatonicum","Bebop Dominant","Raga Khamaj","Desh Malhar","Alhaiya Bilaval","Devagandhari","Bihagara","Maqam Shawq Awir","Gregorian nr.6","Major/Mixolydian mixed","Chinese Eight-Tone","Rast"],
	3767: ["Chromatic Bebop"],
	3773: ["Raga Malgunji","Ramdasi Malhar","Major/Dorian mixed","Blues Enneatonic"],
	3829: ["Taishikicho","Ryo","Raga Chayanat","Lydian/Mixolydian mixed"],
	3837: ["Minor Pentatonic with leading tones"],
	3965: ["Messiaen mode 7 inverse"],
	4013: ["Raga Pilu","Full Minor"],
	4021: ["Raga Pahadi"],
	4029: ["Major/Minor mixed"],
	4095: ["Chromatic","Twelve-tone Chromatic"],
};
